openforcefield/openff-fragmenter

.travis.yml
devtools/conda-recipe/meta.yaml

This PR attempts to fix the failing openeye toolkit import in travis tests.

Fix failing openeye import in travis tests

---

fragmenter/tests/test_torsions.py
fragmenter/torsions.py

This PR adds a formal charge to the JSON molecule definition.

Formal charge

---

devtools/conda-envs/meta.yaml
devtools/conda-recipe/build.sh
examples/example_workflow.json
fragmenter/chemi.py
fragmenter/tests/reference/workflows.json
fragmenter/tests/test_workflow_api.py
fragmenter/workflow_api.py

This PR adds a few changes to allow using the workflow API when skipping fragmentation.

Skip fragmenting

---

docs/examples.rst

fixed syntax error

---

README.md

Adds Zenodo DOI badge to README:

Add Zenodo DOI badge to README

---

fragmenter/data/fgroup_smarts.yml

Provide a brief description of the PR's purpose here.

Fixed SMARTS

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
fragmenter/__init__.py
fragmenter/_version.py
fragmenter/chemi.py
fragmenter/fragment.py
fragmenter/states.py
fragmenter/tests/test_chemi.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_torsions.py
fragmenter/tests/utils.py
fragmenter/torsions.py
fragmenter/utils.py

This PR lints the codebase with black, isort and flake8 to match the rest of the OpenFF repositories.

Lint the codebase with isort, black, flake8

---

fragmenter/chemi.py
fragmenter/fragment.py
fragmenter/states.py
fragmenter/torsions.py
fragmenter/utils.py

This PR removes the custom `logger` method and replaces calls to it with calls to a standard `logger` object to be more consistent with the other OpenFF repos.

Remove the logger utility

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_utilts.py
fragmenter/utils.py

This PR adds utilities to access the fgroup SMARTS patterns from a single location rather than individual functions loading the internal file.

Add utilities to access the fgroup smarts

---

fragmenter/fragment.py

This PR removes the `_get_torsion_quartet`, `_get_ring_and_fgroups`, and `_cap_open_valence` functions from the `PfizerFragmenter` class as they duplicate the same methods from the parent `WBOFragmenter` class, and removes the duplicate `__init__` code.

Remove duplicate code from the Pfizer fragmenter

---

fragmenter/chemi.py
fragmenter/fragment.py
fragmenter/tests/test_chemi.py
fragmenter/tests/test_fragmenter.py

This PR updates the stereochemistry checks / fixes to use the OpenFF toolkit. This required adding a new method, `find_stereocenters`, which itself calls cheminformatic toolkit code directly as the OpenFF toolkit currently does not expose the required API points (see https://github.com/openforcefield/openff-toolkit/issues/903).
This refactor currently fully removes the `_fix_enum_nitrogen` method. As far as I can tell this method offers no additional fixes that the
```
for stereoisomer in _enumerate_stereoisomers(fragment, 200, True, True):
if not self._check_stereo(stereoisomer):
continue
return stereoisomer
```
lines would not catch.
This refactor adds an extra exception to the `_fix_stereo` method. Previously this method was allowed to return even if the stereochemistry could not be …

Refactor stereo checks / fixes to use the OFF toolkit

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

This PR refactors the code which detects ring systems and ortho functional groups to use the OpenFF toolkit. This includes:
* Accessing the ring system directly from the `ring_system` field rather than from data stored on individual atoms which is not possible in the OpenFF toolkit.
* Replacing the ortho group detection code with a simpler SMARTS matching approach. While care was taken to try and ensure that the two approaches are equivalent, the implementations are different enough that subtle differences may have creeped in.

Refactor the ring sytem and ortho group detection

---

fragmenter/fragment.py

This PR updates the `_get_torsion_quartet` method to use the OFF toolkit. There should not be any behaviour changes introduced given the simplicity of the code.

Refactor torsion quartet code to use the OFF toolkit

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml

This PR re-enables the GHA CI on `master` now that #68 has been merged and work is no longer being carried out in the `refactor-main` branch.

Re-enable GHA on master

---

README.md

This PR fixes the CI badge on the README.

Fix CI README badge

---

.readthedocs.yml

This PR aims to fix building documentation on ReadTheDocs.

Fix documentation building on RTD

---

README.md

This PR fleshes out the README with extra usage instructions.

Update the README with additional instructions

---

docs/api.rst
docs/conf.py

Provide a brief description of the PR's purpose here.

Update the RTD module path

---

.pre-commit-config.yaml
openff/fragmenter/_tests/conftest.py
openff/fragmenter/_tests/test_chemi.py
openff/fragmenter/_tests/test_depiction.py
openff/fragmenter/_tests/test_regression.py
openff/fragmenter/_tests/test_utils.py
openff/fragmenter/chemi.py
openff/fragmenter/depiction.py
openff/fragmenter/fragment.py

Provide a brief description of the PR's purpose here.

Suppress warnings in tests

---

.github/workflows/ci.yaml

See https://github.com/openforcefield/openff-utilities/issues/77

Fix micromamba CI

---

.github/workflows/ci.yaml
devtools/conda-envs/test_env.yaml
openff/fragmenter/fragment.py

https://docs.pydantic.dev/latest/changelog/#v11018-2024-08-22

Use new Pydantic v1 backdoor

---

devtools/conda-envs/test_env.yaml

Resolves https://github.com/openforcefield/openff-fragmenter/issues/183

Attempt to fix CI by downpinning away from rdkit 2024.03.6

---

.github/workflows/ci.yaml
devtools/conda-envs/docs.yaml
devtools/conda-envs/test_env.yaml
openff/fragmenter/fragment.py

Use Pydantic V2 API

---

devtools/conda-envs/docs.yaml

Fix docs builds
