fragmenter/fragment.py
fragmenter/tests/reference/butane.smi
fragmenter/tests/test_fragmenter.py
fragmenter/torsions.py
fragmenter/utils.py

Added canonicalization detail to provenance in JSON specs. Below is what the JSON structure looks like for butane:
```
{
"CCCC": {
"canonical_isomeric_SMILES": "CCCC",
"crank_torsion_drives": {
"crank_job_1": {
"crank_specs": {
"model": {
"basis": "aug-cc-pVDZ",
"method": "B3LYP"
},
"options": {
"scf_type": "df"
}
},
"torsion_0": 30,
"torsion_1": 30,
"torsion_2": 30
}
},
"molecule": {
"geometry": [
0.31914281845092773,
-1.093637466430664,
-1.5644147396087646,
0.09283685684204102,
-0.7512494325637817,
-0.10052239894866943,
-0.09279406070709229,
0.7513599395751953,
0.1004934310913086,
-0.290915846824646,
1.0967583656311035,
1.5677818059921265,
-0.5198796391487122,
-0.7551677227020264,
-2.180879592895508,
1.2282583713531494,
-0.6067847013473511,
-1.931321620941162,
0.43323153257369995, …
```

added canonicalization details to provenance

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py
fragmenter/torsions.py
fragmenter/utils.py

This PR expands an incoming molecule to its protonation states, tautomers and stereoisomers. It addressed issues https://github.com/openforcefield/fragmenter/issues/6 and https://github.com/openforcefield/fragmenter/issues/5
The default settings enumerate protonation states and stereoisomers. The results for kinase inhibitors are here:
https://github.com/choderalab/fragmenter_examples/blob/tautomers/tautomer_enumeration/states.xlsx

Expand states

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_torsions.py
fragmenter/torsions.py
fragmenter/utils.py

This PR does the following:
1) Updates `expand_states` to use the newer `OETautomerOptions()` and adds more options to `OEEnumerateTautomers` and `OEEnumerateFormalCharge`.
2) Allows terminal torsion to be separated from mid torsions so they can be driven at a different grid spacing or not driven at all. 
3) Adds several utils function to analyze and visualize bond orders.

Fix expand state and separate terminal torsions

---

fragmenter/fragment.py
fragmenter/tests/reference/butane_crankjob.json
fragmenter/tests/test_torsions.py
fragmenter/torsions.py
fragmenter/utils.py

This PR changes the JSON crank spec structure  by separating mid and terminal torsions. The change also allows for different grid options. Below is the JSON spec for `needed_torsion_drives` and `crank_jobs`:
```
"needed_torsions": { 
"mid": {
"grid_spacing": [30, 120 ...] # Can also be list of list when specifying more than one crank job
"torsion_0": (0, 1, 2, 3), 
"torsion_1": (4, 5, 6 7),
}
"terminal": {
"grid_spacing": None (if we are not driving them)
"torsion_0": (2, 3, 4, 5)
}
}
```
```
"crank_job_0": { 
"mid_torsions" : {
"torsion_0": 30
"torsion_1": 120
"terminal_torsions" : {}
}
}
```
to specify several 1-D torsion scan:
```
"needed_torsions": { 
"mid": {
"grid_spacing": [[30, None, None] , [None, 30, None], [None, None, 30]]
"torsion_0": (0, 1, 2, 3), 
"torsion_1": (4, 5, 6 7), …
```

Allow more complex scan grids

---

README.md
devtools/conda-recipe/meta.yaml
examples/example_workflow.json
fragmenter/chemi.py
fragmenter/torsions.py
fragmenter/utils.py
fragmenter/workflow_api.py

This PR adds the ability to drive stiff torsions such as rings and double bonds. These changes are general enough to accommodate regular geometry optimization in the future. 
The JSON specs were changes as follows:
* The workflow JSON now includes `torsiondrive_static_options` and `optimization_static_options` in the meta section of the workflow and `restricted_optimization_options` was added to the `torsiondrive_input` field. An example of the workflow JSON is [here](https://github.com/openforcefield/fragmenter/blob/workflow/examples/example_workflow.json)
* The JSON for the inputs were changed to include a `type` field to specify if a torsiondrive or optimization job will be run. If it is an optimization job, a …

[WIP] Add the ability to run limited torsion scans on constrained torsions

---

.gitignore
.travis.yml
devtools/conda-envs/meta.yaml
devtools/scripts/conda_env.py
devtools/travis-ci/before_install.sh
fragmenter/chemi.py
fragmenter/tests/test_fractal.py
fragmenter/torsions.py

- Switches testing constructs over to QCF* type via conda-envs which the cookie cutter will likely migrate too as well.
- Adds QCFractal and depends testing, explicitly pulls many QCF dependencies from `conda` rather than accidentals via pip. This will be greatly simplified once we push Fractal out to Conda-forge or similar.
- Pulls tagged geometric/torsiondrives for testing.
- Adds a quick torsion drive test case.

Starts QCFractal Integration Testing

---

.gitignore
.travis.yml
devtools/conda-envs/meta.yaml
devtools/scripts/conda_env.py
devtools/travis-ci/before_install.sh
fragmenter/chemi.py
fragmenter/tests/test_fractal.py
fragmenter/torsions.py

This PR replaces https://github.com/openforcefield/fragmenter/pull/24
* Switches testing constructs over to QCF* type via conda-envs which the cookie cutter will likely migrate too as well.
* Adds QCFractal and depends testing, explicitly pulls many QCF dependencies from conda rather than accidentals via pip. This will be greatly simplified once we push Fractal out to Conda-forge or similar.
* Pulls tagged geometric/torsiondrives for testing.
* Adds a quick torsion drive test case.

Start QCFractal integration testing

---

devtools/conda-envs/meta.yaml
fragmenter/chemi.py
fragmenter/tests/reference/workflows.json
fragmenter/tests/test_chemi.py
fragmenter/tests/test_torsions.py
fragmenter/tests/test_utils.py
fragmenter/tests/test_workflow_api.py
fragmenter/torsions.py
fragmenter/workflow_api.py

Added the ability to start `torsiondrive` from multiple starting conformations. This can speed up optimization and allows for better sampling of minima. 

[WIP] Add option to start torsiondrive with multiple conformations

---

README.md
fragmenter/fragment.py
fragmenter/tests/test_fractal.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_utils.py
fragmenter/tests/test_workflow_api.py

Cleaned up `expand_states` to only generate reasonable tautomers by using [`OEGEtReasonableTautomers`](https://docs.eyesopen.com/toolkits/cpp/quacpactk/OEProtonFunctions/OEGetReasonableTautomers.html#OEProton::OEGetReasonableTautomers). 

Only generate reasonable tautomers

---

fragmenter/fragment.py

WBO minimal fragment was slightly different than Pfizer. The Pfizer scheme keeps all ortho groups to all bonds in the initial group of bonds in the set while the WBO scheme only kept ortho groups to the central bond and their connected bonds. After looking at the results from the benchmark, the data doesn't look compelling enough for this change. 
In this image, the X axis shows how much bigger the Pfizer fragment is (only where the Pfizer minimal fragment is bigger because of this difference). On the Y axis is the difference in their respective distance scores. Positive Y shows that the smaller, WBO fragment has a better score, negative score the larger, Pfizer minimal fragment has a better score. Too many have negative Y values to justify this change.

use Pfizer minimial fragment in WBO fragmentation

---

devtools/conda-envs/meta.yaml
devtools/conda-recipe/meta.yaml
fragmenter/fragment.py

Bugfix for mapping dihedral indices. 
The original atom maps are from the parent molecule. They need to be remapped to the indices in the `canonical_isomeric_explicit_hydrogen_mapped_smiles`. But sometimes some explicit hydrogens are removed when fragmenting so they need to be added back before the dihedral indices are mapped to the fragment's indices.

add explicit hydrogen when mapping dihedral indices

---

devtools/conda-envs/meta.yaml
fragmenter/states.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_states.py
fragmenter/tests/utils.py
fragmenter/utils.py

This PR refactors the stereo enumeration to use the OpenFF toolkit rather than OE directly. This is part of the larger refactoring (#68) effort.
- The RDKit and OE toolkits disagree on whether to treat pyramidal nitrogens as stereocenters and hence this lack of `parity` will also carry through here.

Refactor stereo enumeration to use the OFF toolkit

---

fragmenter/states.py
fragmenter/tests/test_utilts.py
fragmenter/torsions.py
fragmenter/utils.py

This PR refactors the `torsions` module to use the OpenFF toolkit and removes the unused `_find_torsions_from_smarts` and `one_torsion_per_rotatable_bond` methods.
The code produced by the updated `find_torsion_around_bond` is not guaranteed to return the same result after the refactor. This is mainly due to bugs in the old `one_torsion_per_rotatable_bond` method which would occasionally return multiple torsions for the same rotatable bond, and from those the `find_torsion_around_bond` method was not guaranteed to select the torsion with the heaviest end groups as `one_torsion_per_rotatable_bond` intended to return.
Additionally, the `find_torsion_around_bond` method would (likely unintentionally) previously return a `ValueError` if the input `bond` was not rotatable . The current code …

Refactor torsion module to use the OFF toolkit

---

fragmenter/chemi.py
fragmenter/tests/test_chemi.py

This PR adds a new `find_ring_systems` to the `chemi` module which employs `networkx` to determine ring systems. This will in part replace the `WBOFragmenter._find_ring_systems` function.

Add find ring systems utility

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

This PR splits the non-WBO specific code into the `Fragmenter` base class. This enables making the `PfizerFragmenter` independent of the `WBOFragmenter` class given that the Pfizer method does not use WBOs.

Refactor non-WBO code into Fragmenter base class

---

.github/workflows/ci.yaml
devtools/conda-envs/meta.yaml
fragmenter/chemi.py
fragmenter/fragment.py
fragmenter/tests/test_chemi.py
fragmenter/tests/test_fragmenter.py

This PR refactors the `chemi` module to use the OpenFF toolkit for conformer generation and AM1 ELF10 WBO assignment.
While the toolkit should give very similar WBOs to the pure OE approach this may not be guaranteed in all cases - it seems that the older versions of OE will produce slightly different WBOs for the same input conformer when computing them using a newer OE version but the same input conformer.
Further, it is currently the case that the toolkit may give very different WBOs when using the AmberTools backend rather than the OE backend. This is due to differences in how each toolkit both generates conformers and then minimises those conformers prior to computing the AM1 wavefunction.

Refactor the chemi module to use the OFF toolkit

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

This PR isolates the use of OpenEye `OEAtomBondSet` objects to a single method call - `_atom_bond_set_to_mol`. These were only really used when depicting fragments, the code for which has already been removed and would need to be completely re-written after the refactor anyway.

Isolate internal use of atom and bond sets

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_utilts.py
fragmenter/utils.py

This PR updates the valence capping code to use the OFF toolkit. As part of this PR this unused `target_bond` was dropped and a `get_atom_index` convenience method added.

Refactor valence capping to use the OFF toolkit

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

This PR refactors the `_find_rotatable_bonds` function to use the OFF toolkit. Unfortunately the OFF `find_rotatable_bonds` cannot be used here as we need to include rotatable double bonds and filter for terminal bonds.

Use the OFF toolkit to find rotatable bonds

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

While this PR refactors the `WBOFragmenter._build_fragment` method and those methods it depends on to use the OFF toolkit, it goes beyond that by isolating the heuristic code, removes the recursive design pattern, and moves all WBO tolerance logic into the `WBOFragmenter._build_fragment` method.
The refactoring performed here should have several benefits:
* Having the heuristic code in separate methods should in future make it easer to support new heuristics without breaking the existing ones while simultaneously making the methods easier to unit test.
* Having a single location for the WBO tolerance checks makes it clearer where fragmentation decisions are made, and removing the recursive code patterns (which were not needed) should make debugging easier.
Because the refactoring …

Refactor WBO fragment building to use the OFF toolkit

---

fragmenter/chemi.py
fragmenter/fragment.py
fragmenter/tests/test_chemi.py
fragmenter/tests/test_fragmenter.py

This PR refactors the function which creates a fragment molecule from a set of atom and bond indices (`Fragmenter._atom_bond_set_to_mol`) into the `chemi` module and adds an RDKit variant in addition to the OE pathway. 
* The RDKit implementation is less clean ( / potentially more frafile) than the OE one as RDKit does not seem to have a function for retrieving a substructure based on atom / bond indices which will also add hydrogens to account for changes in the valence of any atoms.
* The OE code was modified to include hydrogens which are bound to atoms to include in the substructure search. This is so that those in the final fragment will retain their map indices which should be more helpful and will also more closely match of the output of the RDKit implementation.

Move fragment from indices to chemi and add RDKit variant

---

fragmenter/fragment.py

This PR updates the `_find_ring_systems` to correctly handle the cases where an atom may be part of multiple functional groups based (as defined by the functional group SMARTS patterns), e.g. in a ketone and a amide.

Handle atoms in multiple groups when finding ring systems

---

fragmenter/chemi.py

This PR updates the RDKit based fragment extraction code to be able to handle the case where have re-used a ring based carbon atom as a methyl cap while discarding the rest of the ring (see `_cap_open_valence`).

Fix extracting fragment with methyl cap with RDKit

---

devtools/conda-envs/meta.yaml
fragmenter/data/report-template.html
fragmenter/depiction.py
fragmenter/tests/test_depiction.py

This PR exposes a new `depict_fragments` function in a new `fragmenter.depiction` module which will create a HTML page showing a parent molecule and its associated fragments.
When using OE the output will look similar to:
and when using RDKit:

Add simple HTML and SVG based fragment depiction

---

fragmenter/fragment.py
fragmenter/tests/test_fragmenter.py

This is the first in a series of at least two PRs which aim to make the fragmenter classes stateless, such that the class itself does not keep track of things like the parent molecule, rings systems, etc (see #49, #98).
This PR mainly focuses on making all of the internal functions pure, will keeping the overall API unchanged. Removing the parent `molecule`, `functional_groups`, and `fragments` fields will be handled in the next PR.
The changes made here have made unit testing significantly easier (i.e. one can run each method without worrying whether the main object itself has the correct state), and should making the changes to the API proposed in #98 easier.
(cc @lilyminium @j-wags and @jthorton as these changes may affect you in the long run)

Begin to make fragmenter stateless

---

devtools/conda-envs/meta.yaml

This PR updates the test environment to install the `openff-toolkit` from C-F rather than using `pip` now a new release has been made.

Install the OFF toolkit from C-F for the CI

---

fragmenter/fragment.py
fragmenter/tests/test_chemi.py
fragmenter/tests/test_fragmenter.py
fragmenter/tests/test_utils.py
fragmenter/tests/utils.py
fragmenter/utils.py

This PR adds an argument to the `fragment` method that allows the user to easily choose which toolkit registries should be used by the OpenFF toolkit during the fragmentation. Information about the used toolkits are stored in the provenance dictionary.
```
{'toolkits': [('RDKitToolkitWrapper', '2021.03.1')]}
```

Add argument to set the toolkit registry

---

fragmenter/fragment.py

This PR fixes a bug whereby the `PfizerFragmenter` returns the input molecule in the result object, rather than the canonically ordered parent used in the actual fragmentation.

Fix Pfizer fragmenter returning incorrect parent

---

docs/conf.py
fragmenter/fragment.py
fragmenter/tests/test_regression.py
setup.py
versioneer.py

This PR adds some regression tests for the WBO fragmentation scheme. The WBO examples are molecules that have provided the same fragments using the new code with both AT+RDKIT and OE which are also consistent with those given by fragmenter=0.0.7.

Regression tests

---

openff/fragmenter/tests/conftest.py
openff/fragmenter/tests/test_regression.py

This PR flags the regression tests introduced in #112 as slow running as they can take >10 mins on the CI.

Mark the regression tests as slow

---

openff/fragmenter/fragment.py
openff/fragmenter/tests/__init__.py
openff/fragmenter/tests/test_fragmenter.py

This PR expands the `fragment` method to accept a set of SMARTS patterns that control which bonds to grow fragments around.

Allow custom rotatable bond definitions

---

docs/environment.yml

This PR pins to `sphinx ==4.0.2` to resolve `nbsphinx` compatability issues (see https://github.com/spatialaudio/nbsphinx/issues/584)

Pin sphinx to 4.0.2 for `nbsphinx` compatability

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
openff/fragmenter/tests/test_chemi.py
openff/fragmenter/tests/test_depiction.py

The tests in `test_depiction` used mapped SMILES to define test molecules. However, molecules created using mapped SMILES are expected to have explicit Hs, which these test SMILES didn't. This PR makes the Hs explicit on these input SMILES.

Fix test_depiction now that toolkit doesn't handle radicals

---

docs/conf.py
docs/installation.rst

Adds a link to the [ecosystem install guide](https://docs.openforcefield.org/en/latest/install.html) to the project install guide

Add link to OpenFF install guide

---

.github/workflows/ci.yaml
openff/fragmenter/fragment.py

This PR updates the codebase to work with both Pydantic v1 and v2 and also tests each case.

Test on Pydantic v1 and v2

---

.github/workflows/ci.yaml
openff/fragmenter/_tests/conftest.py
openff/fragmenter/_tests/test_regression.py
pytest.ini

Short story: our projects copy-past [this](https://docs.pytest.org/en/7.1.x/example/simple.html#control-skipping-of-tests-according-to-command-line-option) setup, which does not work when running multiple repos' tests at once. Simply renaming a few should avoid this conflict.
The behavior is conceptually un-changed; slow tests are not run by default but can be turned on with command-line flags.

Avoid duplicating boilerplate `--runslow` argument

---

.github/workflows/ci.yaml

Dependabot can't access the OpenEye secret, so when it merges a pull request without `fail-fast: false`, all CI runs fail.

Maintenance fixes
